### ISSUE TITLE
Native library does not work on ubuntu 16.04 x64

### ISSUE THREAD

**Issue by eiennohito** [irundaia/sbt-sassify#17]
Error:

```
[error] (kotonoha/web-assets:sassify) java.lang.UnsatisfiedLinkError: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by irundaia** [comment]
Apologies for the inconvenience, I'll have a look at it this evening. 

Thanks for the report

**Comment by eiennohito** [comment]
Wait a sec, could be problems with the (sort of weird) local configuration.

**Comment by eiennohito** [comment]
Sorry, my bad, everything works.

**Comment by irundaia** [comment]
That's quite alright, glad you figured it out :)
