### ISSUE TITLE
Publish for sbt 1.0.0?

### ISSUE THREAD

**Issue by ngbinh** [irundaia/sbt-sassify#25]
Looks like we need to wait for sbt-web first https://github.com/sbt/sbt-web/issues/141
http://www.scala-sbt.org/1.0/docs/sbt-1.0-Release-Notes.html#sbt+1.0.0-RC2

**Comment by rpiaggio** [comment]
`sbt-web` is now released for sbt 1.0. Please consider publishing `sbt-sassify` for sbt 1.0 please. Thank you!

**Comment by LogicalTime** [comment]
+1 yes please. Can't use bootstrap 4 beta with SBT 1 without this. Using CentOS.

**Comment by LogicalTime** [comment]
This seems to be done now with version 1.4.10

**Comment by irundaia** [comment]
@LogicalTime did you test it with sbt 1.0.x? If so I’ll close this issue.

**Comment by LogicalTime** [comment]
I'm getting some errors. No Such MethodError  SBT.web.CompileProblems$report

Also one of the most recent version of sbt-web depending has a library compiled with Java 9.

**Comment by LogicalTime** [comment]
I see 1.4.10 was the Java 9 cuplrit. I will try 1.4.11 tomorrow and let you know how it goes. Thanks! 
https://github.com/irundaia/sbt-sassify/issues/28

**Comment by ngbinh** [comment]
fixed on `1.4.11`. Thanks
