### ISSUE TITLE
1.4.10 not working with Java 8

### ISSUE THREAD

**Issue by migo** [irundaia/sbt-sassify#32]
Version 1.4.10 of sbt-sassify does not seem to work with Java 8:

(web/web-assets:sassify) java.lang.UnsupportedClassVersionError: org/irundaia/sass/jna/SassLibrary has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by irundaia** [comment]
I’m sorry for this issue, upgrading to version 1.4.11 should fix this issue. (This is exactly the same code, but it’s been compiled against a different target JDK)

**Comment by abdelrahmanmohamed** [comment]
any updates on that issue

**Comment by irundaia** [comment]
@abdelrahmanmohamed please upgrade to version 1.4.11 or 1.4.12. That should solve this issue.
