### ISSUE TITLE
Compiled output going to unexpected directory?

### ISSUE THREAD

**Issue by yellowstonesoftware** [irundaia/sbt-sassify#33]
Hi
The documentation mentions for the example the compiled sass would be available at public/stylesheets/

It looks like in my Play 2.6.9 application the output goes to target/web/sass/main/stylesheets rather than the expected target/web/public/main/stylesheets. Is there a configuration option I'm missing? 

Thanks!

**Comment by irundaia** [comment]
Hi @peternitro,

I'm sorry for the late response, but could you perhaps share your project setup (at least the folder/package structure and the relevant sbt-sassify settings)?

It's been a while since I last looked at which directory the compiled Sass is output to. I'll have another look at it in the mean while.

**Comment by irundaia** [comment]
@peternitro, I've run a quick test. In my case, the css file is output to both `target/web/sass/main/stylesheets` as well as `target/web/public/main/stylesheets`.

If I remember correctly, sbt-web configures the `sass` directory to be a temporary directory where the sbt-sassify plugin can do it's business. When the plugin is done, the results are copied over to the `public` directory (along with all other web assets coming from other plugins). 

Could you check that the compiled css output is also put in the `public` directory? If not, please provide an example setup with which I can test things.

**Comment by yellowstonesoftware** [comment]
hi @irundaia - thank you for checking, i put together a quick skeleton problem and the compiled sass ended up exactly in the two directories you mentioned. so i think it's safe to say there's something wrong with my specific project, i'll dig in and reopen here if need be, thanks again and apologies for the false alarm :)

**Comment by irundaia** [comment]
No problem, let me know if you've got an example that exhibits the behaviour.

**Comment by lolgab** [comment]
At [Codacy](https://codacy.com) we are moving from sbt-sass to sbt-sassify and I faced the same behaviour.
In our case updating sbt-web from 1.4.3 to 1.4.4 solved the problem. I don't know the root cause though.
