### ISSUE TITLE
Unable to build bootstrap 4

### ISSUE THREAD

**Issue by pschichtel** [irundaia/sbt-sassify#37]
Hi. I just tried to @import bootstrap into my main.scss but it failed with the error below.
Running sassc with the latest libsass works just fine, downgrading libsass to 3.4.9 as used by sassify will trigger the same bug again.

```
$ sassc bootstrap.scss
Error: 1 isn't a valid CSS value.
        on line 90 of vendor/_rfs.scss
>>       $rfs-static: #{$fs / $rfs-rem-value}rem#{$rfs-suffix};

   ---------------------^
```

**Comment by pschichtel** [comment]
Build a version locally against 3.5.5 and that seems to work without problems.

**Comment by pschichtel** [comment]
#38 and #39 resolve this.

**Comment by pschichtel** [comment]
@irundaia Are you still working on this project?

**Comment by irundaia** [comment]
@pschichtel, I’m sorry, I hadn’t seen your PR’s.
I have to say that I haven’t had reason to update this package of the last couple of years. But in case of any feature requests/ PR’s, I intend to perform maintenance.

Thanks for the PR’s I’ll have a look at them now.

**Comment by pschichtel** [comment]
Great to hear. I suspected you just didn't see it.
do you have plans for a fix release already?

**Comment by irundaia** [comment]
I'm testing some things now. If that works, I'll update push the release today.

**Comment by pschichtel** [comment]
Cool, thanks

**Comment by pschichtel** [comment]
btw you linux x86_32 docker image seems to be broken as well, apt couldn't find the repository servers. I personally don't think x86_32 is relevant on dev systems, but I'd say either fix it or remove it.

**Comment by irundaia** [comment]
@pschichtel,

I just released version 1.4.13 of sbt-sassify. This should fix your issues with compiling bootstrap. Could you have a look at whether you have any other issues?

Thanks!

**Comment by pschichtel** [comment]
Great, I will test it this week.

**Comment by pschichtel** [comment]
works, thanks
