### ISSUE TITLE
Use .min.css extension for minified output

### ISSUE THREAD

**Issue by Mat2095** [irundaia/sbt-sassify#44]
When using compression in sbt-less, the output-file will end with .min.css.
https://github.com/sbt/sbt-less/blob/1.1.2/src/main/resources/lessc.js#L49

It would be nice if sbt-sassify could do the same. However I see how this would break existing projects. Maybe it could be added as an option? I'm not sure if that would be the right thing.

**Comment by irundaia** [comment]
I'll try to get a version out today where you can manually set the file extension.

**Comment by irundaia** [comment]
I just released version 1.5.0 with the option to set the file extension. By default it is set to `css` such as not to break older build. Can you check whether this works out for you?

**Comment by Mat2095** [comment]
Yes, it works perfectly. Thank you!
