### ISSUE TITLE
Plugin version for Scala 2.13 not available

### ISSUE THREAD

**Issue by SanityResort** [irundaia/sbt-sassify#45]
We are currently trying to update our project to Play 2.8.x and Scala 2.13. We have this plugin included in our project according to the Play documentation.

Currently the Plugin is not available for Scala 2.13 which blocks our upgrade. Are there any plans or maybe an eta on when the plugin will be available for Scala 2.13

**Comment by irundaia** [comment]
I've been trying to reproduce your issue, but I'm unable to. I've used the playframework g8 template to set up a new play project based on :

| sbt | 1.3.10 |
| scala | 2.13.2 |
| playframework | 2.8.1| 

With that setup I can still compile sass files. If understand correctly, the scala version you setup for your project has nothing to do with the scala version that SBT uses internally (which I think is 2.12.*).
If that is not the case, can you provide a minimal example project that exhibits your problem?

**Comment by Mat2095** [comment]
In our project we are using sbt 1.3.10, scala 2.13.1 and playframework 2.8.1. Sassify 1.4.12 works fine for us.

**Comment by SanityResort** [comment]
Thanks for the quick replys. Actually this is something I was not aware of and it seems this is short coming in our application setups. We will try to look into that.
