### ISSUE TITLE
Build error: Illegal character in path

### ISSUE THREAD

**Issue by nilsklimm** [irundaia/sbt-sassify#5]
I get build errors when there are spaces in the absolute path of the project root.

Works: /home/user/workspace/projectroot
Does not work: /home/user/work space/projectroot

The error message looks similar to this:

[error] /home/user/work space/projectroot/app/assets/stylesheets/somestyles.scss:1: Error: Illegal character in path at index 15: /home/user/work space/projectroot/app/assets/stylesheets/somestyles.scss

**Comment by irundaia** [comment]
I've been having a quick look at it. It seems to be the same issue as listed in [#17](https://github.com/bit3/jsass/issues/17) of jsass. Unfortunately, this issue cannot be solved in this plugin, but it has to be solved in jsass.

I'll be proposing a PR shortly (I hope).

**Comment by irundaia** [comment]
I don't think that there is a clean solution for this since the URI class is used internally in `jsass`. I'm working on implementing the `libsass` interface myself (should be done this weekend).

**Comment by irundaia** [comment]
I've more or less finished the migration.. Unfortunately, the build is failing due to an incorrectly compiled library. Since I've compiled it as a shared library, it has a link error (java.lang.UnsatisfiedLinkError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.18' not found)

@nils81 you wouldn't be able to tell me how I could compile a shared library without depending on source libraries, would you? _crosses fingers_

**Comment by nilsklimm** [comment]
Unfortunately, i have no experience in compiling java and c++. I am a frontend developer :(

**Comment by irundaia** [comment]
Same here, there's a good reason why I'm a java/scala programmer. :'(
I'll have a go at docker.

**Comment by irundaia** [comment]
I've got some issues with loading the native libraries at runtime. All tests succeed. But loading the library from SBT fails. See also [this issue](https://github.com/sbt/sbt/issues/2351)

**Comment by irundaia** [comment]
This issue should have been fixed with the new v1.4.1 release. Can you verify this?

**Comment by irundaia** [comment]
I've tested this under OS X as well as Windows. On both platforms it seems to work. Hence, I'm closing this issue again.
